version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "web"
      POSTGRES_USER: "367363"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./psql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"